drop table if exists cat cascade;
create table cat (
	id integer generated by default as identity,
	name varchar(255),
	evil boolean not null,
	has_whiskers boolean not null,
	length bigint,
	primary key (id)
);

